server:
  port: 8081
  tomcat:
    threads:
      max: 50
    max-connections: 100
    max-http-form-post-size: 120MB
    connection-timeout: 60000

mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  mail:
    host: smtp.qq.com
    username: your-username # 请替换为真实的用户名
    password: your-password # 请替换为真实的密码
    default-encoding: utf-8
    protocol: smtp
    port: 465
    properties:
      mail:
        smtp:
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory
          ssl:
            enable: true

  datasource:
    username: root
    password: 123456 # 请替换为真实的密码
    url: jdbc:mysql://localhost:3306/poetize?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

user:
  code:
    format: your-format # 请替换为实际的格式
  subscribe:
    format: your-format # 请替换为实际的格式

store:
  type: your-store-type # 请替换为实际的存储类型

local:
  enable: true # 根据需要设置
  uploadUrl: C:/pictures/ # 请替换为实际的上传URL
  downloadUrl: C:/pictures/ # 请替换为实际的下载URL

#qiniu:
#  enable: true # 根据需要设置
#  accessKey: your-access-key # 请替换为七牛云的AccessKey
#  secretKey: your-secret-key # 请替换为七牛云的SecretKey
#  bucket: your-bucket-name # 请替换为七牛云的Bucket名称
#  downloadUrl: your-download-url # 请替换为七牛云的下载URL前缀

aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com # OSS的访问端点，这里以杭州区域为例
    accessKeyId: LTAI5t7Uj9gnH9gmqpQn7rWb         # OSS的访问密钥ID
    accessKeySecret: mIJ54oLaKHCsZAy8EZ2ZYE3OYF4H6u  # OSS的访问密钥密钥
    bucketName: poetize-lpj            # OSS的存储桶名称